#!/bin/bash

#By Juri 10/2016

# checking if ethtool is installed and installing it
if [ $(which ethtool 2>/dev/null | grep -v "not found" | wc -l) = 0 ] ; then echo "Ethtool app is not present. Installing..."
if [ $(which yum 2>/dev/null | grep -v "not found" | wc -l) = 0 ] ; then
apt-get update &>/dev/null ; wait ; apt-get -y install ethtool python-pip mtr &> /dev/null ; wait ; else yum -y install ethtool mtr &> /dev/null ; wait ; fi ; fi

PORTnic=$(ip -o link show | awk '{print $2,$9}' | grep UP | awk '{print $1}' | sed 's/:.*//')
PORTspeed=$(ethtool $PORTnic | grep Speed)
PORTduplex=$(ethtool $PORTnic | grep Duplex)
PORTtype="$PORTspeed $PORTduplex"

printf "Duplex Speed: %s \n" "$PORTtype"

if [ "${PORTduplex#*Half}" != "$PORTduplex" ] ; then
if [ -f /etc/network/interfaces ] ; then
read -p " Duplex is Half. Changing... 1Gb speed? Type y for 1Gb or n for 100Mb ==> " $opt Panswer
case $Panswer in
        Y|y) echo "post-up /sbin/ethtool -s eth0 speed 1000 duplex full autoneg off" >> /etc/network/interfaces && service networking restart ;;
        N|n) echo "post-up /sbin/ethtool -s eth0 speed 100 duplex full autoneg off" >> /etc/network/interfaces && service networking restart ;;
        *) echo "Someting wrong. Change manually" ;;
esac
fi
if [ -f /etc/sysconfig/network-scripts/ifcfg-$PORTnic ] ; then
read -p " Duplex is Half. Changing... 1Gb speed? Type y for 1Gb or n for 100Mb ==> " $opt Panswer
case $Panswer in
        Y|y) echo 'ETHTOOL_OPTS="speed 1000 duplex full autoneg off"' >> /etc/sysconfig/network-scripts/ifcfg-$PORTnic && service network restart ;;
        N|n) echo 'ETHTOOL_OPTS="speed 100 duplex full autoneg off"' >> /etc/sysconfig/network-scripts/ifcfg-$PORTnic && service network restart ;;
        *) echo "Someting wrong. Change manually" ;;
esac
fi
fi

genTest=1
echo "Startng speed test. Choose type of test"
echo "1 - Download 1GB from Maidenhead, 2 - Download 1GB from Nottingam, 3 - generic Download/Upload test"
read -p "type 1 or 2 or 3:  " AnsweR1
case $AnsweR1 in
	1) linkD="http://dc5.rapidswitch.com/DC5/1000mb.bin" ;;
	2) linkD="http://dc3.rapidswitch.com/1000mb.bin" ;;
	3) genTest=7 ;;
	*) echo "Wrong answer. Doing default option 1"
	   linkD="http://dc5.rapidswitch.com/DC5/100mb.bin" ;;
esac

if [ $genTest -eq 7 ] ; then
if [ $(which python-pip 2>/dev/null | grep -v "not found" | wc -l) = 0 ] && [ $(which yum 2>/dev/null | grep -v "not found" | wc -l) = 0 ] ; then
apt-get update &>/dev/null ; wait ; apt-get -y install python-pip mtr &> /dev/null ; wait ; fi
#wget -O speedtest-cli https://raw.github.com/sivel/speedtest-cli/master/speedtest_cli.py &> /dev/null
wget -q -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
chmod +x speedtest-cli
./speedtest-cli
rm -f speedtest-cli
else
wget -O /dev/null $linkD
fi

MTRyes=1
read -p "To do MTR Trace? y or n?:  " AnsweR2
case $AnsweR2 in
	Y|y) MTRyes=7 ;;
	N|n) echo "OK" ; exit 1 ;;
	*) echo "wrond answer. exit" ; exit 1 ;;
esac

if [ $MTRyes = 7 ] ; then
if [ $(which mtr 2>/dev/null | grep -v "not found" | wc -l) = 0 ] ; then echo "MTR app is not present. Installing..."
if [ $(which yum 2>/dev/null | grep -v "not found" | wc -l) = 0 ] ; then
apt-get update &>/dev/null ; wait ; apt-get -y install mtr &> /dev/null ; wait ; else yum -y install mtr &> /dev/null ; wait ; fi ; fi

echo "TO which IP should MTR traces go? Or generic DC5 location?"
defaultIP=78.129.207.116
read -p "Type IP address or hit ENTER for default [${defaultIP}] : ==> " AnsweR3
AnsweR3=${AnsweR3:-$defaultIP}

if [[ ! $AnsweR3 =~ ^((25[0-5]|2[0-4][0-9]|[01][0-9][0-9]|[0-9]{1,2})[.]){3}(25[0-5]|2[0-4][0-9]|[01][0-9][0-9]|[0-9]{1,2})$ ]] ; then
#if [[ ! $AnsweR3 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] ; then
echo "wrong IP entered - using default"
AnsweR3=78.129.207.116 ; fi

defaultTraces=100
read -p "Type amount of MTR traces to do or hit ENTER for default [${defaultTraces}] : " AnsweR4
AnsweR4=${AnsweR4:-$defaultTraces}

if ! [[ $AnsweR4 =~ ^[0-9]+$ ]] ; then
   echo "error: Not a valid number - using default 100" >&2 ; AnsweR4=100 ; fi

MTRmode=1
     read -p "To do MTR Trace in backgound (easier to copy) y or n?:  " AnsweR5
     case $AnsweR5 in
              Y|y) MTRmode=7 ;;
              N|n) echo "OK" ;;
              *) echo "wrond answer. doing iteractive" ; MTRmode=2 ;;
     esac

if [ $MTRmode = 7 ] ; then
echo "please wait for couple minutes (MTR traces are happening in background)"
echo "You can do ineractive MTR traces with 1000 packets with command: mtr -rwt -c 1000 78.129.207.116 "

mtr -rw -c $AnsweR4 $AnsweR3
else 
mtr -rwt -c $AnsweR4 $AnsweR3
fi
fi
echo "Finish"
